### ISSUE TITLE
Variables in URL doesn't work anymore

### ISSUE THREAD

**Issue by deluxebear** [kestra-io/plugin-airbyte#105]
### Expected Behavior

![Image](https://github.com/user-attachments/assets/ef7f8296-23ce-40e8-ad7c-7e473ff4f706)

```
id: test3
namespace: vayi.it
tasks:
  - id: message
    type: io.kestra.plugin.core.log.Log
    message: "{{kv('ETL_URL')}}"
  - id: data_ingestion
    type: io.kestra.plugin.airbyte.connections.Sync
    connectionId: e3b1ce92-547c-436f-b1e8-23b6936c12ab
    url: "{{kv('ETL_URL')}}"
```

log:

![Image](https://github.com/user-attachments/assets/fb076428-70f7-40e5-9fce-c5fee3e983d0)

### Environment Information

- Kestra Version: v0.22.3
- Plugin version: v0.22.0
- Operating System (OS / Docker / Kubernetes): k8s
- Java Version (If not docker):
