### ISSUE TITLE
Airbyte url params not being rendered : fails at parsing secret or env variables

### ISSUE THREAD

**Issue by aballiet** [kestra-io/plugin-airbyte#27]
### Expected Behavior

When creating a new flow using Airbyte plugin :

```yaml
id: hubspot_contacts
namespace: airbyte
tasks:
- id: data-ingestion
  type: io.kestra.plugin.airbyte.connections.Sync
  url: "{{ globals['airbyte-url'] }}"
  username: "{{ globals['airbyte-user'] }}"
  password: "{{ globals['airbyte-password'] }}"
  connectionId: 94464cb0-edb5-44fe-a4f7-32d5e127365e
```

We expect `"{{ globals['airbyte-url'] }}"` to be rendered whereas 

### Actual Behaviour

it throws the exception : 

`Illegal character in path at index 0: {{ globals['airbyte-url'] }}`

![image](https://github.com/kestra-io/plugin-airbyte/assets/25565600/91137ce1-0e5d-4aea-8d15-24a57b46b5c3)

### Steps To Reproduce

1. Create a new airbyte flow and try to use a templated value in `url`field

### Environment Information

- Chart kestra-0.5.1
- Operating System (OS / Docker / Kubernetes): kubernetes

### Example flow

```yaml
id: hubspot_contacts
namespace: airbyte
tasks:
- id: data-ingestion
  type: io.kestra.plugin.airbyte.connections.Sync
  url: "{{ globals['airbyte-url'] }}"
  username: "{{ globals['airbyte-user'] }}"
  password: "{{ globals['airbyte-password'] }}"
  connectionId: 94464cb0-edb5-44fe-a4f7-32d5e127365e
```
