### ISSUE TITLE
JsonMapper Airbyte

### ISSUE THREAD

**Issue by cpinelatreinta** [kestra-io/plugin-airbyte#70]
### Expected Behavior

https://kestra-io.slack.com/archives/C03FQKXRK3K/p1709331967684239

### Actual Behaviour

https://kestra-io.slack.com/archives/C03FQKXRK3K/p1709331967684239

### Environment Information

- Kestra Version: 0.15.0
- Plugin version: 0.15.0
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow
```yaml
id: test1231
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋
  - id: airbyte_sync
    type: "io.kestra.plugin.airbyte.connections.Sync"
    url: "{{ secret('AIRBYTE_URL') }}"
    username: "{{ secret('AIRBYTE_USER') }}"
    password: "{{ secret('AIRBYTE_PASSWORD') }}"
    connectionId: d189622c-a38f-4cd6-9baa-b49a2458eb66
```
