### ISSUE TITLE
Airbyte Plugin — Error encoding object [{connectionId=io.kestra.core.runners.RunContextProperty@6fc78736}] to JSON: No serializer found for class io.kestra.core.runners.RunContextProperty and no properties discovered to create BeanSerializer

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-airbyte#97]
### Issue description

User report: "the following flow worked until I ran a docker update (Feb 5th) ( I am using the postgres kestra image)"

```yaml
id: my_airbyte_sync
namespace: acmecorp.customer
tasks:
  - id: airbyte_sync
    type: io.kestra.plugin.airbyte.connections.Sync
    url: http://host.docker.internal:8000/
    connectionId: f3f515b1-2c80-476f-9322-45b3a8844ce8
    username: myusername
    password: mypassword
```

Error:

`
Error encoding object [{connectionId=io.kestra.core.runners.RunContextProperty@6fc78736}] to JSON: No serializer found for class io.kestra.core.runners.RunContextProperty and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ImmutableCollections$Map1["connectionId"])
`
